apiVersion: alb.yc.io/v1alpha1
kind: HttpBackendGroup
metadata:
  name: alb-demo-bg
  namespace: alb
spec:
  backends:
    - name: demo-backend
      weight: 30
      useHttp2: false
      service:
        name: alb-demo-1
        port:
          name: http
      healthChecks:
        - http:
            path: /health # Путь, по которому проверяется работоспособность приложения.
          port: 30081 # Порт, указанный в ресурсе Service типа NodePort для проверки работоспособности приложения.
          healthyThreshold: 1
          unhealthyThreshold: 1
          timeout: 2s
          interval: 5s
