apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-demo-1
  namespace: yc-alb
  labels:
    app: alb-demo-1
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alb-demo-1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: alb-demo-1
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: alb-demo-1
          image: <название_образа_Docker>
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz # Путь, по которому проверяется доступность приложения.
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 2
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: alb-demo-1
  namespace: yc-alb
spec:
  selector:
    app: alb-demo-1
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080

    - name: health
      port: 8080 # Порт сервиса.
      targetPort: 8080 # Порт пода.
      nodePort: 30081 # Порт, по которому проверяется доступность приложения.
